config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),

    path('', base_views.index, name='index'),

    path('common/', include('common.urls')),

]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views

app_name = 'pybo'

urlpatterns = [
    # baes_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    #comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),

    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User

#makemigrations, migrate 명령은 모델의 속성이 추가되거나 변경된 경우에 실행 

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null = True)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    #Answer와 연결되어있으므로 answer(연결모델)_set 으로 연결된 답변 찾을 수 있음 
# -------------------------------------- [edit] ------------------------------------------
    def __str__(self):
        return self.subject
# -------------------------------------- [edit] ------------------------------------------
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null = True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.content
# -------------------------------------- [edit] ------------------------------------------
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)
# -------------------------------------- [edit] ------------------------------------------

pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment


# -------------------------------------- [edit] ------------------------------------------
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
# 모델 폼 객체를 저장하면 연결된 모델의 데이터를 저장할 수 있음
# 장고 모델 폼은 내부 클래스로 Meta 클래스를 반드시 가져야 하며, Meta 클래스에는 모델 폼이 사용할 모델과
# 필드들을 적어야 함
# -------------------------------------- [edit] ------------------------------------------
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }
        #부트스트랩 적용 위해서 -> 불마도 가능? 
# -------------------------------------- [edit] ------------------------------------------
        labels = {
            'subject': '제목',
            'content': '내용',
        }
# -------------------------------------- [edit] ------------------------------------------
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }
# -------------------------------------- [edit] ------------------------------------------
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

pybo/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages

from ..forms import AnswerForm
from ..models import Question, Answer

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)
    
# @login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    # if request.user != answer.author:
    #     messages.error(request, '수정권한이 없습니다')
    #     return redirect('pybo:detail', question_id=answer.question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)

# @login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    # if request.user != answer.author:
    #     messages.error(request, '삭제권한이 없습니다')
    # else:
    #     answer.delete()
    answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from ..models import Question
from django.db.models import Q, Count

def index(request):

    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_voter=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from ..models import Question, Answer, Comment
from ..forms import CommentForm

@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)
    
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form':form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)

# <!------------------------------------------ [edit] --------------------------------------------->

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form':form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages

from ..models import Question
from ..forms import QuestionForm

@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context ={'form': form}
    return render(request, 'pybo/question_form.html', context)

# @login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # if request.user != question.author:
    #     messages.error(request, '수정권한이 없습니다.')
    #     return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now() # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

# @login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # if request.user != question.author:
    #     messages.error(request, '삭제권한이 없습니다')
    #     return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form method="post">
        {% csrf_token %}
{#        {% include "form_errors.html" %}#}
        <div>
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="border-bottom">댓글등록하기</h5>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control" name="content" id="content" rows="3">{{ form.content.value|default_if_none:''}}</textarea>
        </div>
        <button type="submit" class="btn">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}

{% block content %}
    <!-- -------------------------------------- [edit] ------------------------------------------ -->
<div> 
    <h1>{{ question.subject }}</h1>
    <div>{{ question.content|mark }}</div>
    <td>{{ question.author.username }}</td> 
    <td>{{ question.create_date }}</td>
</div>

{% if request.user == question.author %}
    <div class="my-3">
        <a href="{% url 'pybo:question_modify' question.id  %}"
           class="btn btn-sm btn-outline-secondary">수정</a>
        <a href="#" class="delete"
           data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
    </div>
{% endif %}

<!-- 질문 댓글 -->
{% if question.comment_set.count > 0 %}
<div>
{% for comment in question.comment_set.all %}
    <div class = "comment">
        <span style="white-space: pre-line;">{{ comment.content }}</span>
        <span>
            - {{ comment.author}}, {{ comment.create_date}}
            {% if comment.modify_date %}
            (수정:{{ comment.modify_date }})
            {% endif %}
        </span>
        {% if request.user == comment.author %}
        <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">수정</a>
        <a href="#" class="small delete"
            data-uri="{% url 'pybo:comment_delete_question' comment.id %}">삭제</a>
        {% endif %}
    </div>
{% endfor %}
</div>
{% endif %}
    <div>
        <a href="{% url 'pybo:comment_create_question' question.id %}"
            class="small"><small>댓글 추가 ..</small></a>
    </div>
<!-- 질문 댓글 끝-->

    <h5>{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    <div>
        <ul>
            {% for answer in question.answer_set.all %}
            <div> 
                <div>{{ answer.content|mark }}</div>
                {% if answer.modify_date %}
                <td>{{ answer.modify_date }}</td>
                {% endif %}
                <td>{{ answer.create_date }}</td>

            </div>
                {% if request.user == answer.author %}
                <div>
                    <a href="{% url 'pybo:answer_modify' answer.id %}"
                       class="btn">수정</a>
                    <a href="#" class="delete"
                       data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
                </div>
                {% endif %}
    <!-- 답글 댓글 -->
                {% if answer.comment_set.count > 0 %}
                    <div>
                    {% for comment in answer.comment_set.all %}
                        <div class = "comment">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author}}, {{ comment.create_date}}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">수정</a>
                            <a href="#" class="small delete"
                                data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_answer' answer.id %}"
                            class="small"><small>댓글 추가 ..</small></a>
                    </div>
    <!-- 답글 댓글 끝-->
            {% endfor %}
        </ul>
    </div>
    
<!---------------------------------------- [edit] ------------------------------------------ -->

    <form action="{% url 'pybo:answer_create' question.id %}" method="post">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="content" rows="15"></textarea> 
        <input type="submit" value="답변등록">
    </form>

{% endblock %}

{% block script %}
    <script type='text/javascript'>
        $(document).ready(function(){
            $(".delete").on('click', function() {
                if(confirm("정말로 삭제하시겠습니까?")) {
                    location.href = $(this).data('uri');
                }
            });
        });
    </script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 >질문등록</h5>
    <form method="post">
        {% csrf_token %}
<!-- # -------------------------------------- [edit] ------------------------------------------ -->
        <!-- 오류표시 -->
        <!-- alert 부트스트랩 필요  -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 끝-->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

<!-- # -------------------------------------- [edit] ------------------------------------------ -->
        <button type="submit" class="btn">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}

{% block content %}
<!-- -------------------------------------- [edit] ------------------------------------------ -->

{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</li>
        <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject}}</a></li>
        {% if question.answer_set.count > 0 %}
        <span>답변개수: {{ question.answer_set.count }}</span>
        {% endif %}
        <td>{{ question.author.username }}</td> 
        <td>{{ question.create_date }}</td>
    {% endfor %}
    </ul>
    <!-- 페이지 처리 시작 -->
    <ul class="pagination">
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
    <!-- 페이지 리스트 -->
    {% for page_number in question_list.paginator.page_range %}
    {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
    <!-- 이부분 이해가 안됨 ㅎ -->
        {% if page_number == question_list.number %}
        <li class="page-item active" aira-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
    {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
    </li>    
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
    </ul>
    
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}
    <a href="{% url 'pybo:question_create' %}" class="btn">질문 등록하기</a>
<!-- # -------------------------------------- [edit] ------------------------------------------ -->
{% endblock %}